version: '3'

services:
    fweb:
        container_name: fweb
        image: fweb
        build:
            context: ./
            dockerfile: Dockerfile.dev
        environment:
            - REACT_APP_BACKEND=$REACT_APP_BACKEND
        ports:
            - 3000:3000
        stdin_open: true
        volumes:
            - ./.:/usr/src/app
            - fweb-deps:/usr/src/app/node_modules
            - fweb-next:/usr/src/app/.next

volumes:
    fweb-deps:
    fweb-next:
